import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Pencil, Plus, Power, RotateCcw, X } from 'lucide-react'
import { api } from '../lib/api'
import { notify, requestConfirmation } from '../lib/feedback'
import { Button, Card, IconButton, Input, Select } from '../components/ui'
import { PageHeader } from '../components/Page'

export interface CategoriaFinanciera { id:string; codigo:string; nombre:string; descripcion:string|null; naturaleza:string; categoriaPadreId:string|null; esSistema:boolean; claveSistema:string|null; activo:boolean }
const naturalezas=['IngresoOperativo','GastoOperativo','Inversion','AporteCapital','RetiroCapital','FinanciamientoRecibido','PagoPrincipalDeuda','GastoFinanciero']

export function CategoriasFinancierasPagina(){
 const client=useQueryClient(); const [formulario,setFormulario]=useState(false); const [editando,setEditando]=useState<CategoriaFinanciera|null>(null); const [inactivos,setInactivos]=useState(false); const [search,setSearch]=useState('')
 const categorias=useQuery({queryKey:['financial-categories',inactivos,search],queryFn:()=>api<CategoriaFinanciera[]>(`/finanzas/categorias?incluirInactivos=${inactivos}&search=${encodeURIComponent(search)}`)})
 const cerrar=()=>{setFormulario(false);setEditando(null)}
 const guardar=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);try{await api(editando?`/finanzas/categorias/${editando.id}`:'/finanzas/categorias',{method:editando?'PUT':'POST',body:JSON.stringify({nombre:d.get('nombre'),descripcion:d.get('descripcion')||null,naturaleza:d.get('naturaleza'),categoriaPadreId:d.get('padre')||null})});notify({tone:'success',title:'Categoría guardada',message:'La clasificación financiera quedó actualizada.'});cerrar();await client.invalidateQueries({queryKey:['financial-categories']})}catch(error){notify({tone:'error',title:'No se guardó la categoría',message:error instanceof Error?error.message:'Ocurrió un error.'})}}
 const cambiarEstado=async(x:CategoriaFinanciera)=>{if(x.activo&&!await requestConfirmation({title:'Desactivar categoría',message:'La categoría dejará de estar disponible para nuevos movimientos.',confirmLabel:'Desactivar',cancelLabel:'Volver'}))return;try{await api(`/finanzas/categorias/${x.id}${x.activo?'':'/reactivar'}`,{method:x.activo?'DELETE':'POST'});await client.invalidateQueries({queryKey:['financial-categories']})}catch(error){notify({tone:'error',title:'No se actualizó la categoría',message:error instanceof Error?error.message:'Ocurrió un error.'})}}
 return <><PageHeader eyebrow="Finanzas" title="Categorías financieras" description="Clasifica ingresos, gastos, inversiones, capital y financiamiento sin confundir su efecto económico." actions={<Button onClick={()=>{setEditando(null);setFormulario(true)}}><Plus size={17}/>Nueva categoría</Button>}/>
 {formulario&&<Card className="mb-5"><div className="flex justify-between"><h2 className="font-display text-lg font-bold">{editando?'Editar categoría':'Nueva categoría'}</h2><IconButton label="Cerrar formulario" onClick={cerrar}><X size={18}/></IconButton></div><form key={editando?.id??'nueva'} onSubmit={guardar} className="mt-4 grid gap-4 md:grid-cols-2"><Input name="nombre" label="Nombre *" required defaultValue={editando?.nombre}/><Select name="naturaleza" label="Naturaleza *" required defaultValue={editando?.naturaleza??''} disabled={editando?.esSistema}><option value="">Seleccionar…</option>{naturalezas.map(x=><option key={x}>{x}</option>)}</Select><Select name="padre" label="Categoría padre" defaultValue={editando?.categoriaPadreId??''}><option value="">Sin categoría padre</option>{categorias.data?.filter(x=>x.id!==editando?.id&&x.activo).map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombre}</option>)}</Select><Input name="descripcion" label="Descripción" defaultValue={editando?.descripcion??''}/><Button type="submit">Guardar</Button></form></Card>}
 <Card><div className="flex flex-wrap items-end justify-between gap-3"><Input label="Buscar" value={search} onChange={e=>setSearch(e.target.value)}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={inactivos} onChange={e=>setInactivos(e.target.checked)}/>Mostrar inactivas</label></div><div className="mt-4 grid gap-2">{categorias.data?.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><div><b>{x.codigo} · {x.nombre}</b><p className="text-xs text-slate-500">{x.naturaleza}{x.claveSistema?` · ${x.claveSistema}`:''}</p></div><div className="flex gap-2"><IconButton tone="edit" label={`Editar ${x.nombre}`} onClick={()=>{setEditando(x);setFormulario(true)}}><Pencil size={18}/></IconButton>{!x.esSistema&&<IconButton tone={x.activo?'danger':'success'} label={`${x.activo?'Desactivar':'Reactivar'} ${x.nombre}`} onClick={()=>void cambiarEstado(x)}>{x.activo?<Power size={18}/>:<RotateCcw size={18}/>}</IconButton>}</div></div>)}</div></Card></>
}
