import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Line, LineChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../lib/api'
import { formatearMoneda, useMonedaTenant } from '../lib/moneda'
import { Card } from '../components/ui'
import { PageHeader } from '../components/Page'
import type { Entity, PagedResult } from '../types'

type Tab='resumen'|'estado-resultados'|'flujo-caja'|'capital-propietario'|'rentabilidad'|'productivo'
type Categoria={categoriaId:string|null;codigo:string;nombre:string;monto:number;porcentajeSobreTotal:number}
type Resumen={ingresosOperativos:number;gastosOperativos:number;resultadoOperativo:number;gastosFinancieros:number;resultadoDespuesFinanciero:number;inversiones:number;aportesCapital:number;retirosCapital:number;capitalNetoRegistrado:number;financiamientoRecibido:number;pagoPrincipalDeuda:number;apoyoDirectoPropietario:number;flujoCajaNetoPagado:number;margenRealizadoVentas:number;cantidadVentas:number;animalesVendidos:number;nacimientosVivos:number;destetes:number;bajas:number;hatoEnCurso:{cantidadAnimales:number;costoAcumulado:number};autosuficiencia:{mes:string;resultadoOperativo:number;aportesCapital:number;apoyoDirectoPropietario:number;requirioApoyoPropietario:boolean;indicadorAutosuficienciaOperativa:boolean}[];primerMesSinApoyo:string|null}
type EstadoMes={mes:string;ingresosOperativos:number;gastosOperativos:number;resultadoOperativo:number;gastosFinancieros:number;resultadoDespuesFinanciero:number}
type Estado={ingresosOperativos:{total:number;detallePorCategoria:Categoria[]};gastosOperativos:{total:number;detallePorCategoria:Categoria[]};resultadoOperativo:number;gastosFinancieros:{total:number;detallePorCategoria:Categoria[]};resultadoDespuesFinanciero:number;meses:EstadoMes[]}
type Flujo={flujoOperacion:number;flujoInversion:number;flujoCapital:number;flujoFinanciamiento:number;flujoNeto:number;entradasTotales:number;salidasTotales:number;movimientosPendientes:number;montoPendiente:number;movimientosParciales:number;montoNominalParcial:number;meses:{mes:string;flujoOperacion:number;flujoInversion:number;flujoCapital:number;flujoFinanciamiento:number;flujoNeto:number}[]}
type Capital={propietarios:{propietarioId:string;propietario:string;aportesCapital:number;retirosCapital:number;capitalNetoRegistrado:number;gastosOperativosPagadosDirectamente:number;inversionesPagadasDirectamente:number;gastosFinancierosPagadosDirectamente:number;pagoPrincipalPagadoDirectamente:number;apoyoDirectoTotal:number}[];meses:{mes:string;aporteCapital:number;retiroCapital:number;apoyoDirecto:number;resultadoOperativo:number}[]}
type RentaItem={clave:string;nombre:string;animalesVendidos:number;ingresoBruto:number;gastosVenta:number;ingresoNeto:number;costoAcumulado:number;margenRealizado:number;porcentajeMargen:number;precioPromedioVenta:number;margenPromedioAnimal:number;pesoVendidoLibras:number;precioPromedioLibra:number|null}
type Rentabilidad={items:RentaItem[];total:number;pagina:number;tamanoPagina:number;ingresoBruto:number;gastosVenta:number;ingresoNeto:number;costoAcumulado:number;margenRealizado:number}
type Productivo={nacimientosVivos:number;hembrasNacidas:number;machosNacidos:number;destetados:number;hembrasDestetadas:number;machosDestetados:number;vendidos:number;hembrasVendidas:number;machosVendidos:number;bajas:number;transferenciasRecibidas:number;transferenciasEnviadas:number;hembrasNacidasRetenidasAlCierre:number;animalesEnEngordaAlCierre:number;animalesReemplazoAlCierre:number;meses:{mes:string;nacimientos:number;destetes:number;ventas:number;bajas:number}[]}

const hoy=new Date();const iso=(d:Date)=>d.toISOString().slice(0,10);const tabs:[Tab,string][]=[['resumen','Resumen'],['estado-resultados','Estado de resultados'],['flujo-caja','Flujo de caja'],['capital-propietario','Capital por propietario'],['rentabilidad','Rentabilidad'],['productivo','Productivo']]
const escapeCsv=(v:string|number|null)=>`"${String(v??'').replaceAll('"','""')}"`
function descargar(nombre:string,columnas:string[],filas:(string|number|null)[][]){const csv='\ufeff'+[columnas,...filas].map(r=>r.map(escapeCsv).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=nombre;a.click();URL.revokeObjectURL(url)}

export function ReportesGerencialesPagina(){
 const {moneda,cultura}=useMonedaTenant();const dinero=(v:number)=>formatearMoneda(v,moneda,cultura)
 const [tab,setTab]=useState<Tab>('resumen');const [inicio,setInicio]=useState(iso(new Date(hoy.getFullYear(),hoy.getMonth(),1)));const [fin,setFin]=useState(iso(hoy));const [propietario,setPropietario]=useState('');const [dimension,setDimension]=useState('Animal');const [pagina,setPagina]=useState(1);const [anio,setAnio]=useState(hoy.getFullYear())
 const rangoValido=inicio<=fin
 const entidades=useQuery({queryKey:['entidades-reportes'],queryFn:()=>api<PagedResult<Entity>>('/entidades?page=1&pageSize=200')})
 const owner=propietario?`&propietarioId=${propietario}`:'';const params=`fechaInicio=${inicio}&fechaFin=${fin}${owner}`
 const resumen=useQuery({queryKey:['rg','resumen',params],queryFn:()=>api<Resumen>(`/reportes-gerenciales/resumen?${params}`),enabled:rangoValido&&tab==='resumen'})
 const estado=useQuery({queryKey:['rg','estado',params],queryFn:()=>api<Estado>(`/reportes-gerenciales/estado-resultados?${params}`),enabled:rangoValido&&tab==='estado-resultados'})
 const flujo=useQuery({queryKey:['rg','flujo',params],queryFn:()=>api<Flujo>(`/reportes-gerenciales/flujo-caja?${params}`),enabled:rangoValido&&tab==='flujo-caja'})
 const capital=useQuery({queryKey:['rg','capital',params],queryFn:()=>api<Capital>(`/reportes-gerenciales/capital-propietario?${params}`),enabled:rangoValido&&tab==='capital-propietario'})
 const rentaUrl=(p:number,size=20)=>`/reportes-gerenciales/rentabilidad?${params}&dimension=${dimension}&pagina=${p}&tamanoPagina=${size}`
 const renta=useQuery({queryKey:['rg','renta',params,dimension,pagina],queryFn:()=>api<Rentabilidad>(rentaUrl(pagina)),enabled:rangoValido&&tab==='rentabilidad'})
 const productivo=useQuery({queryKey:['rg','productivo',anio,propietario],queryFn:()=>api<Productivo>(`/reportes-gerenciales/productivo?anio=${anio}${owner}`),enabled:tab==='productivo'})
 const exportar=async()=>{
  if(tab==='rentabilidad'){const first=await api<Rentabilidad>(rentaUrl(1,100));const all=[...first.items];for(let p=2;p<=Math.ceil(first.total/100);p++)all.push(...(await api<Rentabilidad>(rentaUrl(p,100))).items);descargar('rentabilidad.csv',['Nombre','Animales vendidos','Ingreso bruto','Gastos venta','Ingreso neto','Costo acumulado','Margen realizado','Margen %','Precio promedio','Margen promedio animal','Peso lb','Precio promedio lb'],all.map(x=>[x.nombre,x.animalesVendidos,x.ingresoBruto,x.gastosVenta,x.ingresoNeto,x.costoAcumulado,x.margenRealizado,x.porcentajeMargen,x.precioPromedioVenta,x.margenPromedioAnimal,x.pesoVendidoLibras,x.precioPromedioLibra]));return}
  if(tab==='estado-resultados'&&estado.data){descargar('estado-resultados.csv',['Bloque','Código','Categoría','Monto','%'],[['Ingresos','','Total',estado.data.ingresosOperativos.total,100],...estado.data.ingresosOperativos.detallePorCategoria.map(x=>['Ingresos',x.codigo,x.nombre,x.monto,x.porcentajeSobreTotal]),['Gastos operativos','','Total',estado.data.gastosOperativos.total,100],...estado.data.gastosOperativos.detallePorCategoria.map(x=>['Gastos operativos',x.codigo,x.nombre,x.monto,x.porcentajeSobreTotal]),['Gastos financieros','','Total',estado.data.gastosFinancieros.total,100],...estado.data.gastosFinancieros.detallePorCategoria.map(x=>['Gastos financieros',x.codigo,x.nombre,x.monto,x.porcentajeSobreTotal])]);return}
  if(tab==='flujo-caja'&&flujo.data){descargar('flujo-caja.csv',['Mes','Operación','Inversión','Capital','Financiamiento','Neto'],flujo.data.meses.map(x=>[x.mes,x.flujoOperacion,x.flujoInversion,x.flujoCapital,x.flujoFinanciamiento,x.flujoNeto]));return}
  if(tab==='capital-propietario'&&capital.data){descargar('capital-propietario.csv',['Propietario','Aportes','Retiros','Capital neto','Gasto directo','Inversión directa','Financiero directo','Principal directo','Apoyo total'],capital.data.propietarios.map(x=>[x.propietario,x.aportesCapital,x.retirosCapital,x.capitalNetoRegistrado,x.gastosOperativosPagadosDirectamente,x.inversionesPagadasDirectamente,x.gastosFinancierosPagadosDirectamente,x.pagoPrincipalPagadoDirectamente,x.apoyoDirectoTotal]));return}
  if(tab==='productivo'&&productivo.data){descargar('productivo.csv',['Mes','Nacimientos','Destetes','Ventas','Bajas'],productivo.data.meses.map(x=>[x.mes,x.nacimientos,x.destetes,x.ventas,x.bajas]));return}
  if(resumen.data)descargar('resumen-gerencial.csv',['Indicador','Valor'],Object.entries(resumen.data).filter(([,v])=>typeof v==='number').map(([k,v])=>[k,v as number]))
 }
 const cards=(values:[string,number,boolean?][])=><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{values.map(([l,v,count])=><Card key={l}><p className="text-sm text-slate-500">{l}</p><p className="mt-2 text-2xl font-bold">{count?v:dinero(v)}</p></Card>)}</div>
 return <><PageHeader eyebrow="Análisis y reportes" title="Reportes gerenciales" description="Resultados financieros, capital, rentabilidad y desempeño productivo del tenant activo."/>
 <Card><div className="grid gap-3 md:grid-cols-4"><label>Fecha inicial<input className="input mt-1 w-full" type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></label><label>Fecha final<input className="input mt-1 w-full" type="date" value={fin} onChange={e=>setFin(e.target.value)}/></label><label>Propietario<select className="input mt-1 w-full" value={propietario} onChange={e=>{setPropietario(e.target.value);setPagina(1)}}><option value="">Todos</option>{entidades.data?.items.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombreCompletoORazonSocial}</option>)}</select></label><button className="btn-primary self-end" onClick={()=>void exportar()}>Exportar CSV</button></div></Card>
 {!rangoValido&&<Card><p className="text-red-600">El rango de fechas no es válido.</p></Card>}
 <div className="my-5 flex gap-2 overflow-x-auto">{tabs.map(([k,l])=><button key={k} className={tab===k?'btn-primary':'btn-secondary'} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==='resumen'&&resumen.data&&<>{cards([['Ingresos operativos',resumen.data.ingresosOperativos],['Gastos operativos',resumen.data.gastosOperativos],['Resultado operativo',resumen.data.resultadoOperativo],['Resultado después financiero',resumen.data.resultadoDespuesFinanciero],['Flujo neto pagado',resumen.data.flujoCajaNetoPagado],['Inversiones',resumen.data.inversiones],['Aportes capital',resumen.data.aportesCapital],['Apoyo directo propietario',resumen.data.apoyoDirectoPropietario],['Margen realizado ventas',resumen.data.margenRealizadoVentas],['Animales vendidos',resumen.data.animalesVendidos,true],['Nacimientos',resumen.data.nacimientosVivos,true],['Destetes',resumen.data.destetes,true],['Costo acumulado hato',resumen.data.hatoEnCurso.costoAcumulado]])}<Card><p>Animales en hato: <b>{resumen.data.hatoEnCurso.cantidadAnimales}</b> · Primer mes autosuficiente sin apoyo: <b>{resumen.data.primerMesSinApoyo??'—'}</b></p></Card></>}
 {tab==='estado-resultados'&&estado.data&&<><Bloque titulo="Ingresos operativos" bloque={estado.data.ingresosOperativos} dinero={dinero}/><Bloque titulo="Gastos operativos" bloque={estado.data.gastosOperativos} dinero={dinero}/>{cards([['Resultado operativo',estado.data.resultadoOperativo]])}<Bloque titulo="Gastos financieros" bloque={estado.data.gastosFinancieros} dinero={dinero}/>{cards([['Resultado después financiero',estado.data.resultadoDespuesFinanciero]])}<Grafica data={estado.data.meses}/></>}
 {tab==='flujo-caja'&&flujo.data&&<>{cards([['Operación',flujo.data.flujoOperacion],['Inversión',flujo.data.flujoInversion],['Capital',flujo.data.flujoCapital],['Financiamiento',flujo.data.flujoFinanciamiento],['Neto',flujo.data.flujoNeto],['Entradas',flujo.data.entradasTotales],['Salidas',flujo.data.salidasTotales]])}<Card><p className="text-sm">Pendientes: {flujo.data.movimientosPendientes} ({dinero(flujo.data.montoPendiente)}). Parciales: {flujo.data.movimientosParciales} ({dinero(flujo.data.montoNominalParcial)}). Estos montos nominales no forman parte del efectivo realizado.</p></Card></>}
 {tab==='capital-propietario'&&capital.data&&<Card><Tabla columnas={['Propietario','Aportes','Retiros','Capital neto','Gasto directo','Inversión directa','Financiero directo','Principal directo','Apoyo total']} filas={capital.data.propietarios.map(x=>[x.propietario,dinero(x.aportesCapital),dinero(x.retirosCapital),dinero(x.capitalNetoRegistrado),dinero(x.gastosOperativosPagadosDirectamente),dinero(x.inversionesPagadasDirectamente),dinero(x.gastosFinancierosPagadosDirectamente),dinero(x.pagoPrincipalPagadoDirectamente),dinero(x.apoyoDirectoTotal)])}/></Card>}
 {tab==='rentabilidad'&&renta.data&&<><Card><label>Dimensión<select className="input ml-2" value={dimension} onChange={e=>{setDimension(e.target.value);setPagina(1)}}>{['Animal','GrupoProductivo','Actividad','Propietario','Finca'].map(x=><option key={x}>{x}</option>)}</select></label></Card><Card><Tabla columnas={['Nombre','Animales','Ingreso bruto','Gastos','Ingreso neto','Costo','Margen','Margen %','Precio prom.','Margen/animal','Peso lb','Precio/lb']} filas={renta.data.items.map(x=>[x.nombre,x.animalesVendidos,dinero(x.ingresoBruto),dinero(x.gastosVenta),dinero(x.ingresoNeto),dinero(x.costoAcumulado),dinero(x.margenRealizado),`${x.porcentajeMargen.toFixed(2)}%`,dinero(x.precioPromedioVenta),dinero(x.margenPromedioAnimal),x.pesoVendidoLibras,x.precioPromedioLibra==null?'—':dinero(x.precioPromedioLibra)])}/><Paginacion pagina={pagina} total={renta.data.total} tamano={renta.data.tamanoPagina} setPagina={setPagina}/></Card></>}
 {tab==='productivo'&&productivo.data&&<><Card><label>Año<select className="input ml-2" value={anio} onChange={e=>setAnio(Number(e.target.value))}>{Array.from({length:10},(_,i)=>hoy.getFullYear()-i).map(x=><option key={x}>{x}</option>)}</select></label></Card>{cards([['Nacimientos vivos',productivo.data.nacimientosVivos,true],['Hembras nacidas',productivo.data.hembrasNacidas,true],['Machos nacidos',productivo.data.machosNacidos,true],['Destetados',productivo.data.destetados,true],['Hembras destetadas',productivo.data.hembrasDestetadas,true],['Machos destetados',productivo.data.machosDestetados,true],['Vendidos',productivo.data.vendidos,true],['Hembras vendidas',productivo.data.hembrasVendidas,true],['Machos vendidos',productivo.data.machosVendidos,true],['Bajas',productivo.data.bajas,true],['Hembras retenidas',productivo.data.hembrasNacidasRetenidasAlCierre,true],['En engorda',productivo.data.animalesEnEngordaAlCierre,true],['En reemplazo',productivo.data.animalesReemplazoAlCierre,true]])}<Card><Tabla columnas={['Mes','Nacimientos','Destetes','Ventas','Bajas']} filas={productivo.data.meses.map(x=>[x.mes,x.nacimientos,x.destetes,x.ventas,x.bajas])}/></Card></>}
 </>
}
function Bloque({titulo,bloque,dinero}:{titulo:string;bloque:{total:number;detallePorCategoria:Categoria[]};dinero:(n:number)=>string}){return <Card><h2 className="mb-3 text-lg font-bold">{titulo}: {dinero(bloque.total)}</h2><Tabla columnas={['Código','Categoría','Monto','%']} filas={bloque.detallePorCategoria.map(x=>[x.codigo,x.nombre,dinero(x.monto),`${x.porcentajeSobreTotal.toFixed(2)}%`])}/></Card>}
function Grafica({data}:{data:EstadoMes[]}){return <Card><div className="h-72"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="mes"/><YAxis/><Tooltip/><Legend/><Line dataKey="ingresosOperativos" stroke="#10b981"/><Line dataKey="gastosOperativos" stroke="#ef4444"/><Line dataKey="resultadoOperativo" stroke="#3b82f6"/></LineChart></ResponsiveContainer></div></Card>}
function Tabla({columnas,filas}:{columnas:string[];filas:(string|number)[][]}){return <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr>{columnas.map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{filas.map((f,i)=><tr className="border-t" key={i}>{f.map((x,j)=><td className="p-3" key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function Paginacion({pagina,total,tamano,setPagina}:{pagina:number;total:number;tamano:number;setPagina:(p:number)=>void}){return <div className="mt-4 flex justify-end gap-3"><button className="btn-secondary" disabled={pagina===1} onClick={()=>setPagina(pagina-1)}>Anterior</button><span>{pagina} / {Math.max(1,Math.ceil(total/tamano))}</span><button className="btn-secondary" disabled={pagina*tamano>=total} onClick={()=>setPagina(pagina+1)}>Siguiente</button></div>}
