import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../lib/api'
import { formatearMoneda, useMonedaTenant } from '../lib/moneda'
import { Card } from '../components/ui'
import { PageHeader } from '../components/Page'

type Tab = 'resumen'|'estado-resultados'|'flujo-caja'|'capital-propietario'|'rentabilidad'|'productivo'
type Serie = { mes:string; ingresos:number; gastosOperativos:number; gastosFinancieros:number; inversiones:number; resultado:number }
type Resumen = { ingresosOperativos:number; gastosOperativos:number; gastosFinancieros:number; resultadoOperativo:number; resultadoNeto:number; inversiones:number; aportesCapital:number; retirosCapital:number; financiamientoRecibido:number; pagoPrincipalDeuda:number; flujoCaja:number; margenVentas:number; ventasConfirmadas:number; animalesVendidos:number; nacimientos:number; destetes:number; bajas:number; animalesHatoEnCurso:number; costoHatoEnCurso:number }
type Estado = { categorias:{categoria:string;monto:number}[]; meses:Serie[]; resultado:number }
type Flujo = { operacion:number; inversion:number; capital:number; financiamiento:number; neto:number; pendiente:number; parcial:number; meses:Serie[] }
type Capital = { propietarios:{propietarioId:string;propietario:string;aportesFormales:number;retiros:number;aportesDirectos:number;saldo:number}[]; meses:Serie[] }
type Rentabilidad = { items:{clave:string;nombre:string;ingresoNeto:number;costoReal:number;margen:number;animales:number}[];total:number;pagina:number;tamanoPagina:number;ingresoNeto:number;costoReal:number;margen:number }
type Productivo = { nacimientos:number;destetes:number;ventas:number;bajas:number;transferenciasRecibidas:number;transferenciasEnviadas:number;inventarioInicial:number;inventarioFinal:number;meses:Serie[] }

const hoy=new Date(); const iso=(d:Date)=>d.toISOString().slice(0,10)
const tabs:[Tab,string][]=[['resumen','Resumen'],['estado-resultados','Estado de resultados'],['flujo-caja','Flujo de caja'],['capital-propietario','Capital por propietario'],['rentabilidad','Rentabilidad'],['productivo','Productivo']]

export function ReportesGerencialesPagina(){
 const {moneda,cultura}=useMonedaTenant(); const dinero=(v:number)=>formatearMoneda(v,moneda,cultura)
 const [tab,setTab]=useState<Tab>('resumen'); const [inicio,setInicio]=useState(iso(new Date(hoy.getFullYear(),hoy.getMonth(),1))); const [fin,setFin]=useState(iso(hoy)); const [dimension,setDimension]=useState('Animal'); const [pagina,setPagina]=useState(1)
 const params=`fechaInicio=${inicio}&fechaFin=${fin}`
 const resumen=useQuery({queryKey:['rg','resumen',params],queryFn:()=>api<Resumen>(`/reportes-gerenciales/resumen?${params}`),enabled:tab==='resumen'})
 const estado=useQuery({queryKey:['rg','estado',params],queryFn:()=>api<Estado>(`/reportes-gerenciales/estado-resultados?${params}`),enabled:tab==='estado-resultados'})
 const flujo=useQuery({queryKey:['rg','flujo',params],queryFn:()=>api<Flujo>(`/reportes-gerenciales/flujo-caja?${params}`),enabled:tab==='flujo-caja'})
 const capital=useQuery({queryKey:['rg','capital',params],queryFn:()=>api<Capital>(`/reportes-gerenciales/capital-propietario?${params}`),enabled:tab==='capital-propietario'})
 const renta=useQuery({queryKey:['rg','renta',params,dimension,pagina],queryFn:()=>api<Rentabilidad>(`/reportes-gerenciales/rentabilidad?${params}&dimension=${dimension}&pagina=${pagina}&tamanoPagina=20`),enabled:tab==='rentabilidad'})
 const productivo=useQuery({queryKey:['rg','productivo',hoy.getFullYear()],queryFn:()=>api<Productivo>(`/reportes-gerenciales/productivo?anio=${hoy.getFullYear()}`),enabled:tab==='productivo'})
 const exportar=()=>{ const data=tab==='resumen'?resumen.data:tab==='estado-resultados'?estado.data:tab==='flujo-caja'?flujo.data:tab==='capital-propietario'?capital.data:tab==='rentabilidad'?renta.data:productivo.data; const blob=new Blob(['\ufeff'+JSON.stringify(data,null,2)],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`reporte-${tab}-${inicio}-${fin}.csv`;a.click();URL.revokeObjectURL(a.href) }
 const cards=(values:[string,number][])=> <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{values.map(([l,v])=><Card key={l}><p className="text-sm text-slate-500">{l}</p><p className="mt-2 text-2xl font-bold">{dinero(v)}</p></Card>)}</div>
 const grafica=(s:Serie[]|undefined)=><Card><div className="h-80"><ResponsiveContainer><LineChart data={s??[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="mes"/><YAxis/><Tooltip formatter={(v)=>dinero(Number(v))}/><Legend/><Line dataKey="ingresos" stroke="#10b981"/><Line dataKey="gastosOperativos" stroke="#ef4444"/><Line dataKey="resultado" stroke="#3b82f6"/></LineChart></ResponsiveContainer></div></Card>
 return <><PageHeader eyebrow="Análisis y reportes" title="Reportes gerenciales" description="Resultados financieros, capital, rentabilidad y desempeño productivo del tenant activo."/>
 <Card><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label>Fecha inicial<input className="input mt-1 w-full" type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></label><label>Fecha final<input className="input mt-1 w-full" type="date" value={fin} onChange={e=>setFin(e.target.value)}/></label><button className="btn-primary self-end" onClick={exportar}>Exportar</button></div></Card>
 <div className="my-5 flex gap-2 overflow-x-auto">{tabs.map(([k,l])=><button key={k} className={tab===k?'btn-primary':'btn-secondary'} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==='resumen'&&resumen.data&&<>{cards([['Ingresos operativos',resumen.data.ingresosOperativos],['Gastos operativos',resumen.data.gastosOperativos],['Resultado neto',resumen.data.resultadoNeto],['Costo del hato en curso',resumen.data.costoHatoEnCurso]])}<Card><div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{[['Ventas',resumen.data.ventasConfirmadas],['Animales vendidos',resumen.data.animalesVendidos],['Nacimientos',resumen.data.nacimientos],['Destetes',resumen.data.destetes],['Bajas',resumen.data.bajas],['Hato actual',resumen.data.animalesHatoEnCurso]].map(([l,v])=><div key={l}><p className="text-sm text-slate-500">{l}</p><b>{v}</b></div>)}</div></Card></>}
 {tab==='estado-resultados'&&estado.data&&<>{cards([['Resultado',estado.data.resultado]])}<Card><div className="h-72"><ResponsiveContainer><BarChart data={estado.data.categorias}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="categoria"/><YAxis/><Tooltip formatter={v=>dinero(Number(v))}/><Bar dataKey="monto" fill="#166534"/></BarChart></ResponsiveContainer></div></Card>{grafica(estado.data.meses)}</>}
 {tab==='flujo-caja'&&flujo.data&&<>{cards([['Operación',flujo.data.operacion],['Inversión',flujo.data.inversion],['Capital',flujo.data.capital],['Financiamiento',flujo.data.financiamiento],['Flujo neto',flujo.data.neto],['Pendiente',flujo.data.pendiente]])}{grafica(flujo.data.meses)}</>}
 {tab==='capital-propietario'&&capital.data&&<Card><Tabla columnas={['Propietario','Capital','Aporte directo','Retiros','Saldo']} filas={capital.data.propietarios.map(x=>[x.propietario,dinero(x.aportesFormales),dinero(x.aportesDirectos),dinero(x.retiros),dinero(x.saldo)])}/></Card>}
 {tab==='rentabilidad'&&renta.data&&<><Card><label>Dimensión<select className="input ml-2" value={dimension} onChange={e=>{setDimension(e.target.value);setPagina(1)}}>{['Animal','GrupoProductivo','Actividad','Propietario','Finca'].map(x=><option key={x}>{x}</option>)}</select></label></Card><Card><Tabla columnas={['Nombre','Ingreso neto','Costo real','Margen','Animales']} filas={renta.data.items.map(x=>[x.nombre,dinero(x.ingresoNeto),dinero(x.costoReal),dinero(x.margen),x.animales])}/><div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" disabled={pagina===1} onClick={()=>setPagina(x=>x-1)}>Anterior</button><span>{pagina} / {Math.max(1,Math.ceil(renta.data.total/renta.data.tamanoPagina))}</span><button className="btn-secondary" disabled={pagina*renta.data.tamanoPagina>=renta.data.total} onClick={()=>setPagina(x=>x+1)}>Siguiente</button></div></Card></>}
 {tab==='productivo'&&productivo.data&&<><Card><Tabla columnas={['Inventario inicial','Nacimientos','Destetes','Ventas','Bajas','Transferencias recibidas','Transferencias enviadas','Inventario final']} filas={[[productivo.data.inventarioInicial,productivo.data.nacimientos,productivo.data.destetes,productivo.data.ventas,productivo.data.bajas,productivo.data.transferenciasRecibidas,productivo.data.transferenciasEnviadas,productivo.data.inventarioFinal]]}/></Card>{grafica(productivo.data.meses)}</>}
 </>
}
function Tabla({columnas,filas}:{columnas:string[];filas:(string|number)[][]}){return <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr>{columnas.map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{filas.map((f,i)=><tr className="border-t" key={i}>{f.map((x,j)=><td className="p-3" key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
