import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, RefreshCw, Trash2 } from 'lucide-react'
import { offlineDb, type SyncQueueItem } from '../lib/offline'
import { runSync } from '../lib/sync'
import { Badge, Button, Card, EmptyState } from '../components/ui'
import { PageHeader } from '../components/Page'

export function SyncPage(){const[items,setItems]=useState<SyncQueueItem[]>([]);const load=async()=>setItems(await offlineDb.queue.orderBy('createdAt').reverse().toArray());useEffect(()=>{void load()},[]);const sync=async()=>{await runSync();await load()};return <><PageHeader eyebrow="Trabajo sin conexión" title="Sincronización" description="Los errores y conflictos permanecen visibles hasta que los resuelvas." actions={<Button onClick={()=>void sync()} disabled={!navigator.onLine}><RefreshCw size={17}/> Sincronizar ahora</Button>}/><Card>{!items.length?<EmptyState title="Todo está sincronizado" detail="Las operaciones que realices sin señal aparecerán aquí."/>:<div className="divide-y divide-slate-100 dark:divide-slate-800">{items.map(item=><div key={item.id} className="flex flex-col justify-between gap-3 py-4 sm:flex-row sm:items-center"><div className="flex items-start gap-3">{item.status==='Sincronizada'?<CheckCircle2 className="text-emerald-600"/>:<AlertTriangle className={item.status==='Error'||item.status==='Conflicto'?'text-red-600':'text-amber-600'}/>}<div><p className="font-semibold">{item.kind}</p><p className="text-xs text-slate-500">{new Date(item.createdAt).toLocaleString('es-GT')} · {item.attempts} intento(s)</p>{item.error&&<p className="mt-1 text-xs text-red-600">{item.error}</p>}</div></div><div className="flex items-center gap-2"><Badge tone={item.status==='Sincronizada'?'success':item.status==='Error'||item.status==='Conflicto'?'danger':'warning'}>{item.status}</Badge>{item.status==='Sincronizada'&&<Button variant="ghost" onClick={()=>void offlineDb.queue.delete(item.id).then(load)} aria-label="Eliminar registro sincronizado"><Trash2 size={16}/></Button>}</div></div>)}</div>}</Card></>}

