import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Power } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { api } from '../lib/api'
import { notify, requestConfirmation } from '../lib/feedback'
import type { Animal, Entity, PagedResult } from '../types'
import { Button, Card, Input, Select } from '../components/ui'
import { PageHeader } from '../components/Page'

interface Envio { id:string; codigo:string; fecha:string; propietarioOrigenId:string; entidadDestinoId:string; motivo:string; estado:'Borrador'|'Confirmado'|'Anulado'; cantidad:number }

export function TransferenciasEnviadasPagina(){
  const [origen,setOrigen]=useState('');const client=useQueryClient()
  const entidades=useQuery({queryKey:['entities'],queryFn:()=>api<PagedResult<Entity>>('/entidades?pageSize=100')})
  const animales=useQuery({queryKey:['animals-external-send',origen],queryFn:()=>api<Animal[]>(`/transferencias/cambios-propiedad/animales-disponibles?propietarioOrigenId=${origen}`),enabled:!!origen})
  const operaciones=useQuery({queryKey:['external-sent'],queryFn:()=>api<Envio[]>('/transferencias/enviadas')})
  const refrescar=()=>Promise.all([client.invalidateQueries({queryKey:['external-sent']}),client.invalidateQueries({queryKey:['animals']})])
  const guardar=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const d=new FormData(form);const ids=d.getAll('animales').map(String);try{await api('/transferencias/enviadas',{method:'POST',body:JSON.stringify({claveIdempotencia:crypto.randomUUID(),fecha:d.get('fecha'),propietarioOrigenId:d.get('origen'),entidadDestinoId:d.get('destino'),motivo:d.get('motivo'),documentoReferencia:d.get('documento')||null,observaciones:d.get('observaciones')||null,animalIds:ids,confirmacionNoComercial:d.get('noComercial')==='on'})});form.reset();setOrigen('');notify({tone:'success',title:'Borrador creado',message:'Los animales continúan activos hasta confirmar la salida.'});await refrescar()}catch(error){notify({tone:'error',title:'No se guardó el envío',message:error instanceof Error?error.message:'Ocurrió un error.'})}}
  const confirmar=async(op:Envio)=>{if(!await requestConfirmation({title:'Confirmar salida externa',message:`Saldrán ${op.cantidad} animal(es) del inventario. No se registrará una venta ni un ingreso.`,confirmLabel:'Confirmar salida',cancelLabel:'Volver'}))return;try{await api(`/transferencias/enviadas/${op.id}/confirmar`,{method:'POST'});notify({tone:'success',title:'Salida confirmada',message:'Los animales quedaron como transferidos fuera y se cerraron sus historiales vigentes.'});await refrescar()}catch(error){notify({tone:'error',title:'No se confirmó',message:error instanceof Error?error.message:'Ocurrió un error.'})}}
  const anular=async(op:Envio)=>{if(!await requestConfirmation({title:'Anular borrador',message:'El borrador quedará anulado sin modificar el inventario.',confirmLabel:'Anular',cancelLabel:'Volver'}))return;try{await api(`/transferencias/enviadas/${op.id}/anular`,{method:'POST',body:JSON.stringify({motivo:'Anulado por el usuario'})});notify({tone:'success',title:'Borrador anulado',message:'No se generó ninguna salida.'});await refrescar()}catch(error){notify({tone:'error',title:'No se pudo anular',message:error instanceof Error?error.message:'Ocurrió un error.'})}}
  const nombre=(id:string)=>entidades.data?.items.find(x=>x.id===id)?.nombreCompletoORazonSocial??id
  return <><PageHeader eyebrow="Transferencias" title="Envíos externos" description="Registra salidas de ganado hacia otra organización cuando no existe compraventa."/><nav className="mb-5 flex flex-wrap gap-2"><NavLink className="rounded-xl border px-4 py-2 text-sm font-semibold" to="/transferencias/cambio-propietario">Cambio interno</NavLink><NavLink className="rounded-xl border px-4 py-2 text-sm font-semibold" to="/transferencias/recibidas">Recibidas</NavLink><NavLink className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white" to="/transferencias/enviadas">Enviadas</NavLink></nav>
  <Card><form onSubmit={e=>void guardar(e)} className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><Input name="fecha" label="Fecha de salida *" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><Select name="origen" label="Propietario local *" value={origen} onChange={e=>setOrigen(e.target.value)} required><option value="">Seleccionar…</option>{entidades.data?.items.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombreCompletoORazonSocial}</option>)}</Select><Select name="destino" label="Entidad externa de destino *" required><option value="">Seleccionar…</option>{entidades.data?.items.filter(x=>x.id!==origen).map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombreCompletoORazonSocial}</option>)}</Select><Input name="motivo" label="Motivo no comercial *" required placeholder="Cesión, devolución, traslado…"/><Input name="documento" label="Documento de traslado"/><Input name="observaciones" label="Observaciones"/></div><fieldset><legend className="text-sm font-semibold">Animales que saldrán *</legend><div className="mt-2 grid max-h-72 gap-2 overflow-y-auto sm:grid-cols-2 lg:grid-cols-3">{animales.data?.map(animal=><label key={animal.id} className="flex gap-2 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-800"><input type="checkbox" name="animales" value={animal.id}/><span><b>{animal.codigoAnimal}</b>{animal.arete?` · ${animal.arete}`:''}<span className="block text-xs text-slate-500">{animal.sexo} · {animal.categoria}</span></span></label>)}</div></fieldset><label className="flex items-start gap-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-950 dark:bg-amber-950/30 dark:text-amber-100"><input className="mt-1" type="checkbox" name="noComercial" required/><span>Confirmo que esta salida no es una venta. No se registrará ningún ingreso financiero.</span></label><Button type="submit">Guardar borrador</Button></form></Card>
  <Card className="mt-5"><h2 className="font-display text-lg font-bold">Envíos registrados</h2><div className="mt-4 grid gap-3">{operaciones.data?.map(op=><div key={op.id} className="flex flex-col gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-800 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{op.codigo} · {op.cantidad} animal(es) · {op.estado}</p><p className="text-xs text-slate-500">{new Date(op.fecha).toLocaleDateString('es-GT')} · {nombre(op.propietarioOrigenId)} → {nombre(op.entidadDestinoId)}</p><p className="mt-1 text-sm">{op.motivo}</p></div>{op.estado==='Borrador'&&<div className="flex gap-2"><button type="button" title="Confirmar" onClick={()=>void confirmar(op)} className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-600 text-white"><CheckCircle2 size={19}/></button><button type="button" title="Anular" onClick={()=>void anular(op)} className="grid h-10 w-10 place-items-center rounded-xl bg-red-600 text-white"><Power size={19}/></button></div>}</div>)}</div></Card></>
}
