import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Power, ArrowLeftRight } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { api } from '../lib/api'
import { notify, requestConfirmation } from '../lib/feedback'
import type { CatalogItem, Entity, Farm, PagedResult, Pasture } from '../types'
import { Button, Card, Input, Select } from '../components/ui'
import { PageHeader } from '../components/Page'

interface Recepcion { id:string; codigo:string; fecha:string; entidadOrigenId:string; propietarioDestinoId:string; referenciaExterna:string; estado:'Borrador'|'Confirmado'|'Anulado'; animalGeneradoId:string|null }
const hoy=()=>new Date().toISOString().slice(0,10)

export function TransferenciasRecibidasPagina(){
  const client=useQueryClient();const [finca,setFinca]=useState('')
  const entidades=useQuery({queryKey:['entities'],queryFn:()=>api<PagedResult<Entity>>('/entidades?pageSize=100')})
  const fincas=useQuery({queryKey:['farms-transfer'],queryFn:()=>api<PagedResult<Farm>>('/fincas?pageSize=100')})
  const potreros=useQuery({queryKey:['pastures-transfer'],queryFn:()=>api<PagedResult<Pasture>>('/potreros?pageSize=100')})
  const razas=useQuery({queryKey:['catalog','razas'],queryFn:()=>api<CatalogItem[]>('/catalogos/razas')})
  const colores=useQuery({queryKey:['catalog','colores'],queryFn:()=>api<CatalogItem[]>('/catalogos/colores')})
  const operaciones=useQuery({queryKey:['external-received'],queryFn:()=>api<Recepcion[]>('/transferencias/recibidas')})
  const refrescar=()=>Promise.all([client.invalidateQueries({queryKey:['external-received']}),client.invalidateQueries({queryKey:['animals']})])
  const guardar=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const d=new FormData(form);try{await api('/transferencias/recibidas',{method:'POST',body:JSON.stringify({claveIdempotencia:crypto.randomUUID(),fecha:d.get('fecha'),entidadOrigenId:d.get('origen'),propietarioDestinoId:d.get('propietario'),referenciaExterna:d.get('referencia'),documentoReferencia:d.get('documento')||null,arete:d.get('arete')||null,sexo:d.get('sexo'),categoria:d.get('categoria'),fechaNacimiento:d.get('nacimiento')||null,razaId:d.get('raza')||null,colorId:d.get('color')||null,fincaId:d.get('finca'),potreroId:d.get('potrero')||null,observaciones:d.get('observaciones')||null,confirmacionNoComercial:d.get('noComercial')==='on'})});form.reset();setFinca('');notify({tone:'success',title:'Borrador creado',message:'Aún no se creó el animal ni se modificó el inventario.'});await refrescar()}catch(error){notify({tone:'error',title:'No se guardó la recepción',message:error instanceof Error?error.message:'Ocurrió un error.'})}}
  const confirmar=async(op:Recepcion)=>{if(!await requestConfirmation({title:'Confirmar recepción externa',message:'Se creará un animal con código local nuevo y una entrada de inventario no comercial.',confirmLabel:'Confirmar entrada',cancelLabel:'Volver'}))return;try{await api(`/transferencias/recibidas/${op.id}/confirmar`,{method:'POST'});notify({tone:'success',title:'Recepción confirmada',message:'El animal y su movimiento de entrada fueron creados.'});await refrescar()}catch(error){notify({tone:'error',title:'No se confirmó',message:error instanceof Error?error.message:'Ocurrió un error.'})}}
  const anular=async(op:Recepcion)=>{if(!await requestConfirmation({title:'Anular borrador',message:'El borrador quedará anulado sin afectar el inventario.',confirmLabel:'Anular',cancelLabel:'Volver'}))return;try{await api(`/transferencias/recibidas/${op.id}/anular`,{method:'POST',body:JSON.stringify({motivo:'Anulado por el usuario'})});notify({tone:'success',title:'Borrador anulado',message:'No se generó ningún movimiento.'});await refrescar()}catch(error){notify({tone:'error',title:'No se pudo anular',message:error instanceof Error?error.message:'Ocurrió un error.'})}}
  const nombre=(id:string)=>entidades.data?.items.find(x=>x.id===id)?.nombreCompletoORazonSocial??id
  return <><PageHeader eyebrow="Transferencias" title="Recepciones externas" description="Registra ganado recibido sin compra. El código local se asigna al confirmar y la identificación externa se conserva."/>
  <nav className="mb-5 flex flex-wrap gap-2"><NavLink className="rounded-xl border px-4 py-2 text-sm font-semibold" to="/transferencias/cambio-propietario"><ArrowLeftRight className="mr-2 inline" size={17}/>Cambio interno</NavLink><NavLink className="rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white" to="/transferencias/recibidas">Recibidas</NavLink></nav>
  <Card><form onSubmit={e=>void guardar(e)} className="grid gap-4"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Input name="fecha" label="Fecha de recepción *" type="date" required defaultValue={hoy()}/><Select name="origen" label="Entidad externa de origen *" required><option value="">Seleccionar…</option>{entidades.data?.items.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombreCompletoORazonSocial}</option>)}</Select><Select name="propietario" label="Propietario local *" required><option value="">Seleccionar…</option>{entidades.data?.items.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombreCompletoORazonSocial}</option>)}</Select><Input name="referencia" label="Código o referencia externa *" required/><Input name="documento" label="Documento de traslado"/><Input name="arete" label="Arete"/><Select name="sexo" label="Sexo *" required><option>Hembra</option><option>Macho</option><option>Desconocido</option></Select><Select name="categoria" label="Categoría *" required><option>Ternera</option><option>Novilla</option><option>Vaca</option><option>Ternero</option><option>Novillo</option><option>Toro</option><option>Otra</option></Select><Input name="nacimiento" label="Fecha de nacimiento" type="date"/><Select name="raza" label="Raza"><option value="">No especificada</option>{razas.data?.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</Select><Select name="color" label="Color"><option value="">No especificado</option>{colores.data?.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</Select><Select name="finca" label="Finca inicial *" required value={finca} onChange={e=>setFinca(e.target.value)}><option value="">Seleccionar…</option>{fincas.data?.items.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombre}</option>)}</Select><Select name="potrero" label="Potrero inicial"><option value="">Sin potrero</option>{potreros.data?.items.filter(x=>x.fincaId===finca).map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombre}</option>)}</Select><Input name="observaciones" label="Observaciones"/></div><label className="flex items-start gap-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-950 dark:bg-amber-950/30 dark:text-amber-100"><input className="mt-1" type="checkbox" name="noComercial" required/><span>Confirmo que esta operación no es una compra. No se creará ningún movimiento financiero.</span></label><Button type="submit">Guardar borrador</Button></form></Card>
  <Card className="mt-5"><h2 className="font-display text-lg font-bold">Recepciones registradas</h2><div className="mt-4 grid gap-3">{operaciones.data?.map(op=><div key={op.id} className="flex flex-col gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-800 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{op.codigo} · {op.referenciaExterna} · {op.estado}</p><p className="text-xs text-slate-500">{new Date(op.fecha).toLocaleDateString('es-GT')} · {nombre(op.entidadOrigenId)} → {nombre(op.propietarioDestinoId)}</p></div>{op.estado==='Borrador'&&<div className="flex gap-2"><button type="button" title="Confirmar" onClick={()=>void confirmar(op)} className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-600 text-white"><CheckCircle2 size={19}/></button><button type="button" title="Anular" onClick={()=>void anular(op)} className="grid h-10 w-10 place-items-center rounded-xl bg-red-600 text-white"><Power size={19}/></button></div>}</div>)}</div></Card></>
}
